# Questions 1:
### Create a numpy array starting from 2 till 50 with a stepsize of 3.

In [4]:
import numpy as np
data = np.arange(2,50,3)
print("Array from 2 t 50 with stepsize of 3 =",data)

Array from 2 t 50 with stepsize of 3 = [ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


# Questions 2:
### Accept two lists of 5 elements each from the user. Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.

In [49]:
import numpy as np

u1 = []
for i in range(5):
    n = input("Enter your 1st list =")
    u1.append(n)

u1 = np.array(u1)
print("\n Your 1st list =",u1)
print()
u2 = []
for j in range(5):
    o = input("Enter your 2nd list =")
    u2.append(o)

u2 = np.array(u2)
print("\n Your 2st list =",u2)

u3 = np.append(u1,u2)

u3.sort()

print("\n Concatenated and Sorted Output =",u3)

Enter your 1st list =1
Enter your 1st list =5
Enter your 1st list =47
Enter your 1st list =5
Enter your 1st list =6

 Your 1st list = ['1' '5' '47' '5' '6']
Enter your 2nd list =5
Enter your 2nd list =5
Enter your 2nd list =5
Enter your 2nd list =4
Enter your 2nd list =4

 Your 2st list = ['5' '5' '5' '4' '4']

 Concatenated and Sorted Output = ['1' '4' '4' '47' '5' '5' '5' '5' '5' '6']


# Questions 3:
### Write a code snippet to find the dimensions of a ndarray and its size.

In [27]:
import numpy as np
a = np.array([[[1,2,3],[1,2,3]],[[12,3,4],[2,1,3]]])

print("shape = ",np.shape(a))
print("dimensions = ",len(a.shape))
print("Size =",np.size(a))

shape =  (2, 2, 3)
dimensions =  3
Size = 12


# Questions 4:

### How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet Hint: np.newaxis, np.expand_dims

In [42]:
import numpy as np

a = np.arange(12)
print(a)
print(a.shape)
print("dimensions = ",len(a.shape))

b = a.reshape(3,4)
print(b)
print(b.shape)
print("dimensions = ",len(b.shape))

c = b[:,np.newaxis]
print(c)
print(c.shape)
print("dimensions = ",len(c.shape))

d = c[np.newaxis,:]
print(d)
print(d.shape)
print("dimensions = ",len(d.shape))

e = np.expand_dims(d,axis=0)
print(e)
print(e.shape)
print("dimensions = ",len(e.shape))

[ 0  1  2  3  4  5  6  7  8  9 10 11]
(12,)
dimensions =  1
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)
dimensions =  2
[[[ 0  1  2  3]]

 [[ 4  5  6  7]]

 [[ 8  9 10 11]]]
(3, 1, 4)
dimensions =  3
[[[[ 0  1  2  3]]

  [[ 4  5  6  7]]

  [[ 8  9 10 11]]]]
(1, 3, 1, 4)
dimensions =  4
[[[[[ 0  1  2  3]]

   [[ 4  5  6  7]]

   [[ 8  9 10 11]]]]]
(1, 1, 3, 1, 4)
dimensions =  5


# Questions 5:
### Consider two square numpy arrays. Stack them vertically and horizontally. Hint: Use vstack(), hstack()

In [47]:
a = np.array([range(i,i+4) for i in [2,4,5,6]])
b = np.array([range(i,i+4) for i in [7,8,9,10]])
print(a)
print(b)

[[2 3 4 5]
 [4 5 6 7]
 [5 6 7 8]
 [6 7 8 9]]
[[ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]]


In [51]:
avs = np.vstack([a,b])
print(avs)

[[ 2  3  4  5]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]]


In [52]:
ahs = np.hstack([a,b])
print(ahs)

[[ 2  3  4  5  7  8  9 10]
 [ 4  5  6  7  8  9 10 11]
 [ 5  6  7  8  9 10 11 12]
 [ 6  7  8  9 10 11 12 13]]


In [56]:
bvs = np.vstack([b,a])
print(bvs)

[[ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [ 2  3  4  5]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]]


In [57]:
bhs = np.hstack([b,a])
print(bhs)

[[ 7  8  9 10  2  3  4  5]
 [ 8  9 10 11  4  5  6  7]
 [ 9 10 11 12  5  6  7  8]
 [10 11 12 13  6  7  8  9]]


# Questions 6:
### How to get unique items and counts of unique items?

In [66]:
import numpy as np

# reuisng above arrays
print(avs)
print()
print(bhs)

[[ 2  3  4  5  7  8  9 10]
 [ 4  5  6  7  8  9 10 11]
 [ 5  6  7  8  9 10 11 12]
 [ 6  7  8  9 10 11 12 13]]

[[ 7  8  9 10  2  3  4  5]
 [ 8  9 10 11  4  5  6  7]
 [ 9 10 11 12  5  6  7  8]
 [10 11 12 13  6  7  8  9]]


In [63]:
np.unique(avs)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [65]:
np.size(bhs)

32